export const QUOTES = [
  "Cada día es una nueva oportunidad de convertirte en la mejor versión de ti mismo.",
  "El éxito no es final, el fracaso no es fatal. Lo que cuenta es el coraje de continuar.",
  "Pequeñas acciones consistentes crean grandes resultados.",
  "Tu único competidor eres el tú de ayer.",
  "La disciplina es el puente entre metas y logros.",
  "Haz hoy lo que otros no quieren hacer para tener mañana lo que otros no pueden tener.",
  "El dolor de la disciplina es menor que el dolor del arrepentimiento.",
  "No esperes la motivación, actúa y la motivación llegará.",
  "Una hora de esfuerzo vale más que un día de intenciones.",
  "La constancia vence a la brillantez.",
  "No se trata de ser perfecto, se trata de ser mejor que ayer.",
  "El camino al éxito está pavimentado con hábitos consistentes.",
  "Cada vez que te esfuerzas, te conviertes en alguien diferente.",
  "Las grandes cosas nunca vienen de la zona de confort.",
  "Primero forma el hábito, luego el hábito te forma a ti.",
  "El secreto de salir adelante es empezar.",
  "Cuida de tu cuerpo, es el único lugar donde tienes que vivir.",
  "Duerme temprano, levántate con propósito, muévete con intención.",
  "El esfuerzo de hoy es el resultado de mañana.",
  "No hay atajo hacia ningún lugar que valga la pena llegar.",
  "Transforma tus miedos en combustible.",
  "La grandeza no es algo que encuentras, es algo que construyes.",
  "Cada representación cuenta. Cada repetición importa.",
  "El cuerpo logra lo que la mente cree.",
  "Enfócate en el progreso, no en la perfección.",
  "Tus hábitos de hoy son tu identidad de mañana.",
  "No eres tus pensamientos, eres tus acciones.",
  "La motivación te arranca, el hábito te mantiene en movimiento.",
  "Sé la persona que necesitabas cuando eras más joven.",
  "El mejor momento para empezar fue ayer. El segundo mejor momento es ahora.",
  "Cada día que no avanzas es un día que alguien más se adelanta.",
  "Tu mente es tu arma más poderosa. Entrénala.",
  "La versión más fuerte de ti aún no ha llegado.",
  "No te compares con otros. Compárate con quien eras ayer.",
  "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
  "Cuando sientas ganas de rendirte, recuerda por qué empezaste.",
  "La energía fluye hacia donde va la atención.",
  "Gana primero la mañana, gana el día.",
  "El tiempo pasa de todas formas. Úsalo bien.",
  "Invertir en ti mismo nunca es un desperdicio.",
  "Una vida extraordinaria está hecha de días ordinarios extraordinariamente bien vividos.",
  "No busques el camino sin obstáculos, busca la fuerza para superarlos.",
  "Tu futuro yo te lo agradecerá.",
  "La paciencia y la perseverancia tienen un efecto mágico.",
  "Haz que cada día cuente.",
  "El progreso requiere práctica. La práctica requiere paciencia.",
  "Cree en el proceso, confía en el tiempo.",
  "Actúa como la persona en la que quieres convertirte.",
  "Las decisiones de hoy determinan el destino de mañana.",
  "Trabaja en silencio, deja que tus resultados hablen.",
  "La disciplina es libertad disfrazada.",
  "Cuanto más sudaras en entrenamiento, menos sangrarás en combate.",
  "Sueña en grande, trabaja duro, mantente enfocado.",
  "La vida no premia a los que esperan, premia a los que actúan.",
  "Ser promedio es una elección. La excelencia también lo es.",
  "Tu cuerpo puede soportar casi cualquier cosa. Es tu mente la que necesitas convencer.",
  "La rutina construye el carácter.",
  "El amanecer es la recompensa para los que madrugaron.",
  "No esperes que las cosas sucedan. Haz que sucedan.",
  "Las personas exitosas hacen lo que las personas no exitosas no quieren hacer.",
  "El compromiso contigo mismo es el más importante de todos.",
];

export function getDailyQuote(): string {
  const start = new Date(new Date().getFullYear(), 0, 0);
  const now = new Date();
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  return QUOTES[dayOfYear % QUOTES.length];
}
